# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: Surrogate Modeling Toolbox
    url: https://smt.readthedocs.io/en/latest/index.html

# navigation menu
menu:
  - name: home
    slug: home
    url: /main
  - name: benchmark
    slug: benchmark
    url: /#data
  - name: challenge
    slug: challenge
    url: /challenge
  - name: support
    slug: support
    url: /support
  - name: publish
    slug: publish
    url: /publish

# widgets
widgets:
  - about
  - links
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
